-- =====================================================================
-- Release: 02_05_2026
-- Migration: 2026_05_02_add_db_schema_logs_module.sql
--
-- Intent
--   Register the new admin page "DB Schema Logs" (route /db-schema-logs)
--   in the role-based access control system by inserting a row into
--   public.modules with name 'db-schema-logs'. This is the module key the
--   ProtectedRoute / sidebar use to gate access to the page; until this
--   row exists, no role (other than super-admin) can be granted view
--   access via the Roles & Permissions UI, because that UI lists modules
--   straight from public.modules.
--
--   Page itself was added in the same release; this migration only
--   registers its permission entry.
--
-- Schema affected
--   public.modules                 -- one new row, no DDL
--
-- Idempotency
--   Wrapped in a transaction. The INSERT is guarded by a NOT EXISTS
--   check on name = 'db-schema-logs' (there is no UNIQUE index on
--   public.modules.name in the .NET-managed schema, so we cannot use
--   ON CONFLICT). Re-running the migration is a no-op once the row is
--   present.
--
--   public.modules.id is a GENERATED BY DEFAULT AS IDENTITY column
--   (sequence: public."Module_Id_seq"), so we deliberately omit it from
--   the column list and let the sequence assign the next value.
--
-- Rollback
--   DELETE FROM public.modules WHERE name = 'db-schema-logs';
--   (Will cascade to public.module_access_permissions rows for any role
--    that was granted this module — re-granting requires re-running this
--    migration and re-saving the role from the Roles UI.)
-- =====================================================================

BEGIN;

INSERT INTO public.modules (name, category, sort_order, created_at)
SELECT 'db-schema-logs', 'site-config', 24, now()
WHERE NOT EXISTS (
    SELECT 1 FROM public.modules WHERE name = 'db-schema-logs'
);

COMMIT;
