using AutoMapper;
using Invest.Core.Dtos;
using Invest.Core.Models;

namespace Invest.Core.Mappings;

public class CampaignMappingProfile : Profile
{
    public CampaignMappingProfile()
    {
        CreateMap<CampaignDto, Campaign>()
            .ForMember(i => i.Status, x => x.MapFrom(src => src.Status))
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.ContactInfoAddress, x => x.MapFrom(src => src.ContactInfoAddress))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.MinimumInvestment, x => x.MapFrom(src => src.MinimumInvestment))
            .ForMember(i => i.Website, x => x.MapFrom(src => src.Website))
            .ForMember(i => i.ContactInfoEmailAddress, x => x.MapFrom(src => src.ContactInfoEmailAddress))
            .ForMember(i => i.InvestmentInformationalEmail, x => x.MapFrom(src => src.InvestmentInformationalEmail))
            .ForMember(i => i.ContactInfoFullName, x => x.MapFrom(src => src.ContactInfoFullName))
            .ForMember(i => i.ContactInfoPhoneNumber, x => x.MapFrom(src => src.ContactInfoPhoneNumber))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Terms, x => x.MapFrom(src => src.Terms))
            .ForMember(i => i.Themes, x => x.MapFrom(src => src.Themes))
            .ForMember(i => i.InvestmentTypes, x => x.MapFrom(src => src.InvestmentTypes))
            .ForMember(i => i.SDGs, x => x.MapFrom(src => src.SDGs))
            .ForMember(i => i.ApprovedBy, x => x.MapFrom(src => src.ApprovedBy))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));

        CreateMap<Campaign, CampaignDto>()
            .ForMember(i => i.MetaDescription, x => x.MapFrom(src => src.MetaDescription))
            .ForMember(i => i.MetaTitle, x => x.MapFrom(src => src.MetaTitle))
            .ForMember(i => i.DebtInterestRate, x => x.MapFrom(src => src.DebtInterestRate))
            .ForMember(i => i.DebtMaturityDate, x => x.MapFrom(src => src.DebtMaturityDate))
            .ForMember(i => i.DebtPaymentFrequency, x => x.MapFrom(src => src.DebtPaymentFrequency))
            .ForMember(i => i.EquityTargetReturn, x => x.MapFrom(src => src.EquityTargetReturn))
            .ForMember(i => i.FundTerm, x => x.MapFrom(src => src.FundTerm))
            .ForMember(i => i.EquitySecurityType, x => x.MapFrom(src => src.EquitySecurityType))
            .ForMember(i => i.EquityValuation, x => x.MapFrom(src => src.EquityValuation))
            .ForMember(i => i.InvestmentTypeCategory, x => x.MapFrom(src => src.InvestmentTypeCategory))
            .ForMember(i => i.FeaturedInvestment, x => x.MapFrom(src => src.FeaturedInvestment))
            .ForMember(i => i.AssociatedFundId, x => x.MapFrom(src => src.AssociatedFundId))
            .ForMember(i => i.IsPartOfFund, x => x.MapFrom(src => src.IsPartOfFund))
            .ForMember(i => i.NetworkDescription, x => x.MapFrom(src => src.NetworkDescription))
            .ForMember(i => i.FundraisingCloseDate, x => x.MapFrom(src => src.FundraisingCloseDate))
            .ForMember(i => i.ReferredToCataCap, x => x.MapFrom(src => src.ReferredToCataCap))
            .ForMember(i => i.Status, x => x.MapFrom(src => src.Status))
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.ContactInfoAddress, x => x.MapFrom(src => src.ContactInfoAddress))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.MinimumInvestment, x => x.MapFrom(src => src.MinimumInvestment))
            .ForMember(i => i.Website, x => x.MapFrom(src => src.Website))
            .ForMember(i => i.ContactInfoEmailAddress, x => x.MapFrom(src => src.ContactInfoEmailAddress))
            .ForMember(i => i.InvestmentInformationalEmail, x => x.MapFrom(src => src.InvestmentInformationalEmail))
            .ForMember(i => i.ContactInfoFullName, x => x.MapFrom(src => src.ContactInfoFullName))
            .ForMember(i => i.ContactInfoPhoneNumber, x => x.MapFrom(src => src.ContactInfoPhoneNumber))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Terms, x => x.MapFrom(src => src.Terms))
            .ForMember(i => i.Themes, x => x.MapFrom(src => src.Themes))
            .ForMember(i => i.InvestmentTypes, x => x.MapFrom(src => src.InvestmentTypes))
            .ForMember(i => i.SDGs, x => x.MapFrom(src => src.SDGs))
            .ForMember(i => i.ApprovedBy, x => x.MapFrom(src => src.ApprovedBy))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));

        CreateMap<CampaignDto, CampaignCardDto>()
            .ForMember(i => i.Status, x => x.MapFrom(src => src.Status))
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Themes, x => x.MapFrom(src => src.Themes))
            .ForMember(i => i.InvestmentTypes, x => x.MapFrom(src => src.InvestmentTypes))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));

        CreateMap<CampaignDto, CampaignCardDtov2>()
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));

        CreateMap<CampaignCardDto, CampaignDto>()
            .ForMember(i => i.Status, x => x.MapFrom(src => src.Status))
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Themes, x => x.MapFrom(src => src.Themes))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));

        CreateMap<CampaignDto, InvestmentDto>()
            .ForMember(d => d.Raised, opt => opt.Ignore())
            .ForMember(d => d.Investors, opt => opt.Ignore())
            .ForMember(d => d.DaysSinceCreated, opt => opt.Ignore())
            .ForMember(d => d.ProjectedReturn, opt => opt.Ignore())
            .ForMember(d => d.LatestInvestorAvatar, opt => opt.Ignore())
            .ForMember(d => d.Themes, opt => opt.Ignore())
            .ForMember(d => d.Image, opt => opt.Ignore());

        CreateMap<CampaignDto, PublicCampaignDto>()
            .ForMember(i => i.AddedTotalAdminRaised, x => x.MapFrom(src => src.AddedTotalAdminRaised))
            .ForMember(i => i.MetaDescription, x => x.MapFrom(src => src.MetaDescription))
            .ForMember(i => i.MetaTitle, x => x.MapFrom(src => src.MetaTitle))
            .ForMember(i => i.NetworkDescription, x => x.MapFrom(src => src.NetworkDescription))
            .ForMember(i => i.ReferredToCataCap, x => x.MapFrom(src => src.ReferredToCataCap))
            .ForMember(i => i.Status, x => x.MapFrom(src => src.Status))
            .ForMember(i => i.Target, x => x.MapFrom(src => src.Target))
            .ForMember(i => i.ContactInfoAddress, x => x.MapFrom(src => src.ContactInfoAddress))
            .ForMember(i => i.ContactInfoAddress2, x => x.MapFrom(src => src.ContactInfoAddress2))
            .ForMember(i => i.Description, x => x.MapFrom(src => src.Description))
            .ForMember(i => i.MinimumInvestment, x => x.MapFrom(src => src.MinimumInvestment))
            .ForMember(i => i.Website, x => x.MapFrom(src => src.Website))
            .ForMember(i => i.ContactInfoEmailAddress, x => x.MapFrom(src => src.ContactInfoEmailAddress))
            .ForMember(i => i.InvestmentInformationalEmail, x => x.MapFrom(src => src.InvestmentInformationalEmail))
            .ForMember(i => i.ContactInfoFullName, x => x.MapFrom(src => src.ContactInfoFullName))
            .ForMember(i => i.ContactInfoPhoneNumber, x => x.MapFrom(src => src.ContactInfoPhoneNumber))
            .ForMember(i => i.Name, x => x.MapFrom(src => src.Name))
            .ForMember(i => i.Terms, x => x.MapFrom(src => src.Terms))
            .ForMember(i => i.Themes, x => x.MapFrom(src => src.Themes))
            .ForMember(i => i.InvestmentTypes, x => x.MapFrom(src => src.InvestmentTypes))
            .ForMember(i => i.SDGs, x => x.MapFrom(src => src.SDGs))
            .ForMember(i => i.ApprovedBy, x => x.MapFrom(src => src.ApprovedBy))
            .ForMember(i => i.Property, x => x.MapFrom(src => src.Property))
            .ForMember(i => i.Id, x => x.MapFrom(src => src.Id));
    }
}
