CREATE TABLE public.account_balance_change_logs (
  id bigint NOT NULL DEFAULT nextval('accountbalancechangelogs_id_seq'::regclass),
  user_id text NOT NULL,
  old_value numeric,
  user_name text NOT NULL,
  new_value numeric,
  change_date timestamp with time zone NOT NULL,
  investment_name text,
  payment_type text,
  group_id integer,
  pending_grants_id integer,
  transaction_status text,
  reference text,
  campaign_id integer,
  comment text,
  asset_based_payment_request_id integer,
  zip_code text,
  fees numeric NOT NULL DEFAULT 0.0,
  gross_amount numeric NOT NULL DEFAULT 0.0,
  net_amount numeric NOT NULL DEFAULT 0.0,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT account_balance_change_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_accountbalancechangelogs_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_accountbalancechangelogs_assetbasedpaymentrequest_assetbased FOREIGN KEY (asset_based_payment_request_id) REFERENCES public.asset_based_payment_requests(id),
  CONSTRAINT fk_accountbalancechangelogs_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_accountbalancechangelogs_pendinggrants_pendinggrantsid FOREIGN KEY (pending_grants_id) REFERENCES public.pending_grants(id)
);
CREATE TABLE public.ach_payment_requests (
  id bigint NOT NULL DEFAULT nextval('achpaymentrequests_id_seq'::regclass),
  email text NOT NULL,
  full_name text NOT NULL,
  campaign_id integer,
  amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT ach_payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_achpaymentrequests_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.api_error_logs (
  id bigint NOT NULL DEFAULT nextval('apierrorlog_id_seq'::regclass),
  message text,
  stack_trace text,
  path text,
  method text,
  controller text,
  action text,
  parameters text,
  request_body text,
  user_name text,
  operating_system text,
  device_type text,
  browser text,
  country text,
  region text,
  client_ip text,
  proxy_ip_chain text,
  environment text,
  trace_id text,
  created_at timestamp with time zone NOT NULL,
  inner_exception_message text,
  inner_exception_stack_trace text,
  CONSTRAINT api_error_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.approvers (
  id bigint NOT NULL DEFAULT nextval('approvedby_id_seq'::regclass),
  name text NOT NULL DEFAULT ''::text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT approvers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_approvedby_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.asset_based_payment_request_notes (
  id bigint NOT NULL DEFAULT nextval('assetbasedpaymentrequestnotes_id_seq'::regclass),
  request_id integer NOT NULL,
  note text,
  old_status text,
  new_status text,
  created_by text,
  created_at date NOT NULL,
  CONSTRAINT asset_based_payment_request_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_assetbasedpaymentrequestnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_assetbasedpaymentrequestnotes_assetbasedpaymentrequest_reque FOREIGN KEY (request_id) REFERENCES public.asset_based_payment_requests(id)
);
CREATE TABLE public.asset_based_payment_requests (
  id bigint NOT NULL DEFAULT nextval('assetbasedpaymentrequest_id_seq'::regclass),
  user_id text NOT NULL,
  campaign_id integer,
  asset_type_id integer NOT NULL,
  asset_description text,
  approximate_amount numeric NOT NULL,
  received_amount numeric NOT NULL,
  contact_method text NOT NULL,
  contact_value text NOT NULL,
  status text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone,
  updated_by text,
  reference text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT asset_based_payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_assetbasedpaymentrequest_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_assetbasedpaymentrequest_aspnetusers_updatedby FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT fk_assetbasedpaymentrequest_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_assetbasedpaymentrequest_assettype_assettypeid FOREIGN KEY (asset_type_id) REFERENCES public.asset_types(id),
  CONSTRAINT fk_assetbasedpaymentrequest_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.asset_types (
  id bigint NOT NULL DEFAULT nextval('assettype_id_seq'::regclass),
  type text NOT NULL,
  CONSTRAINT asset_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('auditlogs_id_seq'::regclass),
  table_name text,
  record_id text,
  action_type text,
  old_values text,
  new_values text,
  changed_columns text,
  updated_by text,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.campaign_groups (
  campaigns_id integer NOT NULL,
  groups_id integer NOT NULL,
  CONSTRAINT campaign_groups_pkey PRIMARY KEY (campaigns_id, groups_id),
  CONSTRAINT fk_campaigndtogroup_campaigns_campaignsid FOREIGN KEY (campaigns_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_campaigndtogroup_groups_groupsid FOREIGN KEY (groups_id) REFERENCES public.groups(id)
);
CREATE TABLE public.campaigns (
  id bigint NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass),
  name text,
  description text,
  themes text,
  sdgs text,
  investment_types text,
  terms text,
  minimum_investment text,
  website text,
  contact_info_full_name text,
  contact_info_address text,
  contact_info_email_address text,
  contact_info_phone_number text,
  target text,
  status text,
  image_file_name text,
  pdf_file_name text,
  logo_file_name text,
  approved_by text,
  group_for_private_access_id integer,
  is_active boolean,
  email_sends boolean,
  tile_image_file_name text,
  stage integer,
  property text,
  added_total_admin_raised integer,
  original_pdf_file_name text,
  created_date timestamp with time zone,
  modified_date timestamp with time zone,
  expected_total numeric,
  has_existing_investors boolean,
  mission_and_vision text,
  personalized_thank_you text,
  fundraising_close_date text,
  city text,
  contact_info_address_2 text,
  impact_assets_funding_status text,
  investment_role text,
  state text,
  user_id text,
  zip_code text,
  investment_informational_email text,
  referred_to_catacap text,
  network_description text,
  associated_fund_id integer,
  is_part_of_fund boolean,
  country text,
  other_country_address text,
  featured_investment boolean,
  debt_interest_rate numeric,
  debt_maturity_date date,
  debt_payment_frequency text,
  equity_security_type text,
  equity_target_return numeric,
  equity_valuation numeric,
  fund_term date,
  investment_type_category text,
  meta_description text,
  meta_title text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT fk_campaigns_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_campaigns_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_campaigns_groups_groupforprivateaccessid FOREIGN KEY (group_for_private_access_id) REFERENCES public.groups(id)
);
CREATE TABLE public.catacap_teams (
  id bigint NOT NULL DEFAULT nextval('catacapteam_id_seq'::regclass),
  first_name text NOT NULL,
  last_name text NOT NULL,
  designation text NOT NULL,
  description text NOT NULL,
  image_file_name text,
  linkedin_url text,
  is_management boolean,
  display_order integer NOT NULL,
  created_by text,
  modified_by text,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT catacap_teams_pkey PRIMARY KEY (id),
  CONSTRAINT fk_catacapteam_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_catacapteam_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_catacapteam_aspnetusers_modifiedby FOREIGN KEY (modified_by) REFERENCES public.users(id)
);
CREATE TABLE public.completed_investment_details (
  id bigint NOT NULL DEFAULT nextval('completedinvestmentsdetails_id_seq'::regclass),
  date_of_last_investment date NOT NULL,
  campaign_id integer NOT NULL,
  investment_detail text,
  amount numeric,
  type_of_investment text,
  donors integer,
  themes text,
  created_by text NOT NULL,
  created_on timestamp with time zone NOT NULL,
  modified_on timestamp with time zone,
  site_configuration_id integer,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  investment_vehicle text,
  CONSTRAINT completed_investment_details_pkey PRIMARY KEY (id),
  CONSTRAINT fk_completedinvestmentsdetails_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_completedinvestmentsdetails_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_completedinvestmentsdetails_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_completedinvestmentsdetails_siteconfiguration_siteconfigurat FOREIGN KEY (site_configuration_id) REFERENCES public.site_configurations(id)
);
CREATE TABLE public.completed_investment_notes (
  id bigint NOT NULL DEFAULT nextval('completedinvestmentnotes_id_seq'::regclass),
  completed_investment_id integer,
  note text,
  created_by text,
  created_at date NOT NULL,
  new_amount numeric NOT NULL DEFAULT 0.0,
  old_amount numeric NOT NULL DEFAULT 0.0,
  transaction_type integer,
  CONSTRAINT completed_investment_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_completedinvestmentnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_completedinvestmentnotes_completedinvestmentsdetails_complet FOREIGN KEY (completed_investment_id) REFERENCES public.completed_investment_details(id)
);
CREATE TABLE public.countries (
  id bigint NOT NULL DEFAULT nextval('country_id_seq'::regclass),
  name text NOT NULL,
  is_active boolean,
  sort_order integer NOT NULL,
  code text NOT NULL DEFAULT ''::text,
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.daf_providers (
  id bigint NOT NULL DEFAULT nextval('dafproviders_id_seq'::regclass),
  provider_name text,
  provider_url text,
  is_active boolean,
  CONSTRAINT daf_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.disbursal_request_notes (
  id bigint NOT NULL DEFAULT nextval('disbursalrequestnotes_id_seq'::regclass),
  disbursal_request_id integer,
  note text,
  created_by text,
  created_at date NOT NULL,
  CONSTRAINT disbursal_request_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_disbursalrequestnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_disbursalrequestnotes_disbursalrequest_disbursalrequestid FOREIGN KEY (disbursal_request_id) REFERENCES public.disbursal_requests(id)
);
CREATE TABLE public.disbursal_requests (
  id bigint NOT NULL DEFAULT nextval('disbursalrequest_id_seq'::regclass),
  user_id text NOT NULL,
  campaign_id integer,
  role text,
  mobile text,
  distributed_amount numeric NOT NULL,
  impact_assets_funding_previously text,
  investment_remain_open text,
  receive_date date,
  pitch_deck text,
  investment_document text,
  created_at timestamp with time zone NOT NULL,
  investment_document_name text,
  pitch_deck_name text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  quote text,
  status integer NOT NULL DEFAULT 1,
  CONSTRAINT disbursal_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_disbursalrequest_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_disbursalrequest_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_disbursalrequest_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.ef_migrations_history (
  migration_id text NOT NULL,
  product_version text NOT NULL,
  CONSTRAINT ef_migrations_history_pkey PRIMARY KEY (migration_id)
);
CREATE TABLE public.email_template_variables (
  id bigint NOT NULL DEFAULT nextval('emailtemplatevariable_id_seq'::regclass),
  category integer NOT NULL,
  variable_name text NOT NULL,
  email_template_id integer NOT NULL,
  CONSTRAINT email_template_variables_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_templates (
  id bigint NOT NULL DEFAULT nextval('emailtemplate_id_seq'::regclass),
  name text NOT NULL,
  subject text NOT NULL,
  body_html text NOT NULL,
  category integer NOT NULL,
  status integer NOT NULL,
  is_deleted boolean,
  created_by text,
  modified_by text,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  receiver text,
  trigger_action text,
  deleted_at timestamp with time zone,
  deleted_by text,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT fk_emailtemplate_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id bigint NOT NULL DEFAULT nextval('event_id_seq'::regclass),
  title text NOT NULL,
  description text NOT NULL,
  registration_link text,
  event_time text,
  event_date date NOT NULL,
  status boolean,
  created_by text,
  modified_by text,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  image text,
  image_file_name text,
  duration text,
  type text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_event_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_event_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_event_aspnetusers_modifiedby FOREIGN KEY (modified_by) REFERENCES public.users(id)
);
CREATE TABLE public.faqs (
  id bigint NOT NULL DEFAULT nextval('faq_id_seq'::regclass),
  category integer NOT NULL,
  question text,
  answer text,
  status boolean,
  display_order integer NOT NULL,
  created_by text,
  modified_by text,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT faqs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_faq_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.form_submission_notes (
  id bigint NOT NULL DEFAULT nextval('formsubmissionnotes_id_seq'::regclass),
  form_submission_id integer,
  note text,
  old_status text,
  new_status text,
  created_by text,
  created_at date NOT NULL,
  CONSTRAINT form_submission_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_formsubmissionnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_formsubmissionnotes_formsubmission_formsubmissionid FOREIGN KEY (form_submission_id) REFERENCES public.form_submissions(id)
);
CREATE TABLE public.form_submissions (
  id bigint NOT NULL DEFAULT nextval('formsubmission_id_seq'::regclass),
  form_type integer NOT NULL,
  first_name text,
  last_name text,
  email text,
  description text,
  created_at timestamp with time zone NOT NULL,
  is_deleted boolean,
  target_raise_amount text,
  launch_partners text,
  self_raise_amount_range text,
  status integer NOT NULL DEFAULT 1,
  deleted_at timestamp with time zone,
  deleted_by text,
  CONSTRAINT form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_formsubmission_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.group_account_balances (
  id bigint NOT NULL DEFAULT nextval('groupaccountbalance_id_seq'::regclass),
  user_id text NOT NULL DEFAULT ''::text,
  group_id integer NOT NULL,
  balance numeric NOT NULL,
  last_updated timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT group_account_balances_pkey PRIMARY KEY (id),
  CONSTRAINT fk_groupaccountbalance_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_groupaccountbalance_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_groupaccountbalance_groups_groupid FOREIGN KEY (group_id) REFERENCES public.groups(id)
);
CREATE TABLE public.groups (
  id bigint NOT NULL DEFAULT nextval('groups_id_seq'::regclass),
  name text,
  website text,
  description text,
  is_approuve_required boolean,
  owner_id text,
  is_deactivated boolean,
  picture_file_name text,
  identifier text,
  original_balance numeric,
  is_corporate_group boolean,
  is_private_group boolean,
  champions_and_catalysts text,
  leaders text,
  background_picture_file_name text,
  created_at timestamp with time zone,
  modified_at timestamp with time zone,
  our_why_description text,
  video_link text,
  did_you_know text,
  featured_group boolean,
  group_themes text,
  meta_description text,
  meta_title text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT groups_pkey PRIMARY KEY (id),
  CONSTRAINT fk_groups_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_groups_aspnetusers_ownerid FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.investment_feedbacks (
  id bigint NOT NULL DEFAULT nextval('investmentfeedback_id_seq'::regclass),
  user_id text NOT NULL,
  themes text,
  additional_themes text,
  interested_investment_type text,
  risk_tolerance integer,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT investment_feedbacks_pkey PRIMARY KEY (id),
  CONSTRAINT fk_investmentfeedback_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_investmentfeedback_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.investment_notes (
  id bigint NOT NULL DEFAULT nextval('investmentnotes_id_seq'::regclass),
  campaign_id integer,
  note text,
  created_by text,
  created_at date NOT NULL,
  new_status text,
  old_status text,
  CONSTRAINT investment_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_investmentnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_investmentnotes_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.investment_requests (
  id bigint NOT NULL DEFAULT nextval('investmentrequest_id_seq'::regclass),
  current_step integer NOT NULL,
  status integer NOT NULL,
  country text,
  user_id text,
  website text,
  organization_name text,
  currently_raising boolean,
  investment_types text,
  investment_themes text,
  t_he_me_description text,
  capital_raised text,
  referenceable_investors text,
  has_donor_commitment boolean,
  soft_circled_amount numeric NOT NULL,
  time_li_n_e text,
  campaign_goal numeric NOT NULL,
  role text,
  referral_source text,
  logo_file_name text,
  hero_image_file_name text,
  pitch_deck_file_name text,
  investment_terms text,
  why_back_your_investment text,
  modified_by text,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  is_deleted boolean,
  hero_image text,
  logo text,
  pitch_deck text,
  deleted_at timestamp with time zone,
  deleted_by text,
  CONSTRAINT investment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_investmentrequest_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_investmentrequest_aspnetusers_modifiedby FOREIGN KEY (modified_by) REFERENCES public.users(id),
  CONSTRAINT fk_investmentrequest_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.investment_tag_mappings (
  id bigint NOT NULL DEFAULT nextval('investmenttagmapping_id_seq'::regclass),
  tag_id integer NOT NULL,
  campaign_id integer NOT NULL,
  CONSTRAINT investment_tag_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_investmenttagmapping_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_investmenttagmapping_investmenttag_tagid FOREIGN KEY (tag_id) REFERENCES public.investment_tags(id)
);
CREATE TABLE public.investment_tags (
  id bigint NOT NULL DEFAULT nextval('investmenttag_id_seq'::regclass),
  tag text NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT investment_tags_pkey PRIMARY KEY (id),
  CONSTRAINT fk_investmenttag_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.investment_types (
  id bigint NOT NULL DEFAULT nextval('investmenttypes_id_seq'::regclass),
  name text,
  CONSTRAINT investment_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leader_groups (
  id bigint NOT NULL DEFAULT nextval('leadergroup_id_seq'::regclass),
  user_id text NOT NULL,
  group_id integer NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT leader_groups_pkey PRIMARY KEY (id),
  CONSTRAINT fk_leadergroup_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_leadergroup_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_leadergroup_groups_groupid FOREIGN KEY (group_id) REFERENCES public.groups(id)
);
CREATE TABLE public.module_access_permissions (
  id bigint NOT NULL DEFAULT nextval('moduleaccesspermission_id_seq'::regclass),
  module_id integer NOT NULL,
  role_id text NOT NULL,
  manage boolean,
  delete boolean,
  updated_by text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone,
  CONSTRAINT module_access_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_moduleaccesspermission_aspnetroles_roleid FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT fk_moduleaccesspermission_aspnetusers_updatedby FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT fk_moduleaccesspermission_module_moduleid FOREIGN KEY (module_id) REFERENCES public.modules(id)
);
CREATE TABLE public.modules (
  id bigint NOT NULL DEFAULT nextval('module_id_seq'::regclass),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  category text,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT modules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.news (
  id bigint NOT NULL DEFAULT nextval('news_id_seq'::regclass),
  title text NOT NULL,
  description text,
  news_type_id integer,
  audience_id integer,
  t_he_me_id integer,
  image_file_name text,
  news_link text,
  status boolean,
  created_by text,
  modified_by text,
  news_date date,
  created_at timestamp with time zone NOT NULL,
  modified_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT news_pkey PRIMARY KEY (id),
  CONSTRAINT fk_news_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.pending_grant_notes (
  id bigint NOT NULL DEFAULT nextval('pendinggrantnotes_id_seq'::regclass),
  pending_grant_id integer,
  note text,
  old_status text,
  new_status text,
  created_by text,
  created_at date NOT NULL,
  CONSTRAINT pending_grant_notes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_pendinggrantnotes_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_pendinggrantnotes_pendinggrants_pendinggrantid FOREIGN KEY (pending_grant_id) REFERENCES public.pending_grants(id)
);
CREATE TABLE public.pending_grants (
  id bigint NOT NULL DEFAULT nextval('pendinggrants_id_seq'::regclass),
  user_id text NOT NULL,
  amount text NOT NULL,
  daf_provider text NOT NULL,
  daf_name text,
  campaign_id integer,
  invested_sum text,
  status text,
  created_date timestamp with time zone,
  modified_date timestamp with time zone,
  amount_after_fees numeric,
  grant_amount numeric,
  total_invested_amount numeric,
  rejected_by text,
  rejection_date timestamp with time zone,
  rejection_memo text,
  reference text,
  address text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT pending_grants_pkey PRIMARY KEY (id),
  CONSTRAINT fk_pendinggrants_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_pendinggrants_aspnetusers_rejectedby FOREIGN KEY (rejected_by) REFERENCES public.users(id),
  CONSTRAINT fk_pendinggrants_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_pendinggrants_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.recommendations (
  id bigint NOT NULL DEFAULT nextval('recommendations_id_seq'::regclass),
  user_email text,
  user_full_name text,
  campaign_id integer,
  status text,
  amount numeric,
  date_created timestamp with time zone,
  pending_grants_id integer,
  rejected_by text,
  rejection_date timestamp with time zone,
  rejection_memo text,
  user_id text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_recommendations_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_recommendations_aspnetusers_rejectedby FOREIGN KEY (rejected_by) REFERENCES public.users(id),
  CONSTRAINT fk_recommendations_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_recommendations_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_recommendations_pendinggrants_pendinggrantsid FOREIGN KEY (pending_grants_id) REFERENCES public.pending_grants(id)
);
CREATE TABLE public.requests (
  id bigint NOT NULL DEFAULT nextval('requests_id_seq'::regclass),
  request_owner_id text,
  user_to_follow_id text,
  group_to_follow_id integer,
  status text,
  created_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_requests_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_requests_aspnetusers_requestownerid FOREIGN KEY (request_owner_id) REFERENCES public.users(id),
  CONSTRAINT fk_requests_aspnetusers_usertofollowid FOREIGN KEY (user_to_follow_id) REFERENCES public.users(id),
  CONSTRAINT fk_requests_groups_grouptofollowid FOREIGN KEY (group_to_follow_id) REFERENCES public.groups(id)
);
CREATE TABLE public.return_details (
  id bigint NOT NULL DEFAULT nextval('returndetails_id_seq'::regclass),
  return_master_id integer NOT NULL,
  user_id text NOT NULL,
  investment_amount numeric NOT NULL,
  percentage_of_total_investment numeric NOT NULL,
  return_amount numeric NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT return_details_pkey PRIMARY KEY (id),
  CONSTRAINT fk_returndetails_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_returndetails_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_returndetails_returnmasters_returnmasterid FOREIGN KEY (return_master_id) REFERENCES public.return_masters(id)
);
CREATE TABLE public.return_masters (
  id bigint NOT NULL DEFAULT nextval('returnmasters_id_seq'::regclass),
  campaign_id integer NOT NULL,
  created_by text NOT NULL,
  return_amount numeric NOT NULL,
  total_investors integer,
  total_investment_amount numeric NOT NULL,
  memo_note text,
  status text,
  private_debt_start_date date,
  private_debt_end_date date,
  post_date date NOT NULL,
  created_on timestamp with time zone NOT NULL,
  CONSTRAINT return_masters_pkey PRIMARY KEY (id),
  CONSTRAINT fk_returnmasters_aspnetusers_createdby FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_returnmasters_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.role_claims (
  id bigint NOT NULL DEFAULT nextval('aspnetroleclaims_id_seq'::regclass),
  role_id text NOT NULL,
  claim_type text,
  claim_value text,
  CONSTRAINT role_claims_pkey PRIMARY KEY (id),
  CONSTRAINT fk_aspnetroleclaims_aspnetroles_roleid FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.roles (
  id text NOT NULL,
  name text,
  normalized_name text,
  concurrency_stamp text,
  is_super_admin boolean,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scheduled_email_logs (
  id bigint NOT NULL DEFAULT nextval('scheduledemaillogs_id_seq'::regclass),
  pending_grant_id integer NOT NULL,
  user_id text NOT NULL,
  reminder_type text,
  error_message text,
  s_en_t_date timestamp with time zone NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT scheduled_email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_scheduledemaillogs_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_scheduledemaillogs_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_scheduledemaillogs_pendinggrants_pendinggrantid FOREIGN KEY (pending_grant_id) REFERENCES public.pending_grants(id)
);
CREATE TABLE public.scheduler_logs (
  id bigint NOT NULL DEFAULT nextval('schedulerlogs_id_seq'::regclass),
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  day3_email_count integer NOT NULL,
  week2_email_count integer NOT NULL,
  error_message text,
  CONSTRAINT scheduler_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sdgs (
  id bigint NOT NULL DEFAULT nextval('sdgs_id_seq'::regclass),
  name text NOT NULL DEFAULT ''::text,
  CONSTRAINT sdgs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_configurations (
  id bigint NOT NULL DEFAULT nextval('siteconfiguration_id_seq'::regclass),
  key text NOT NULL,
  value text NOT NULL,
  type text NOT NULL DEFAULT ''::text,
  additional_details text,
  image text,
  image_name text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT site_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_siteconfiguration_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.slugs (
  id bigint NOT NULL DEFAULT nextval('slug_id_seq'::regclass),
  reference_id integer NOT NULL,
  type integer NOT NULL,
  value text,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT slugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_values (
  id bigint NOT NULL DEFAULT nextval('systemvalues_id_seq'::regclass),
  name text NOT NULL,
  value text NOT NULL,
  CONSTRAINT system_values_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id bigint NOT NULL DEFAULT nextval('testimonial_id_seq'::regclass),
  display_order integer NOT NULL,
  perspective_text text,
  description text,
  metrics text,
  role text,
  organization_name text,
  user_id text,
  created_at timestamp with time zone NOT NULL,
  status boolean,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT fk_testimonial_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_testimonial_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.themes (
  id bigint NOT NULL DEFAULT nextval('themes_id_seq'::regclass),
  name text NOT NULL,
  mandatory boolean,
  image_file_name text,
  description text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT themes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_themes_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_claims (
  id bigint NOT NULL DEFAULT nextval('aspnetuserclaims_id_seq'::regclass),
  user_id text NOT NULL,
  claim_type text,
  claim_value text,
  CONSTRAINT user_claims_pkey PRIMARY KEY (id),
  CONSTRAINT fk_aspnetuserclaims_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_investments (
  id bigint NOT NULL DEFAULT nextval('userinvestments_id_seq'::regclass),
  user_id text,
  campaign_name text,
  payment_type text,
  log_trigger_e_d boolean,
  campaign_id integer,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT user_investments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_userinvestments_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_userinvestments_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_userinvestments_campaigns_campaignid FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.user_logins (
  login_provider text NOT NULL,
  provider_key text NOT NULL,
  provider_display_name text,
  user_id text NOT NULL,
  CONSTRAINT user_logins_pkey PRIMARY KEY (login_provider, provider_key),
  CONSTRAINT fk_aspnetuserlogins_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_notifications (
  id bigint NOT NULL DEFAULT nextval('usersnotifications_id_seq'::regclass),
  title text NOT NULL,
  description text NOT NULL,
  url_to_redirect text NOT NULL,
  is_read boolean,
  target_user_id text NOT NULL,
  picture_file_name text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT user_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_usersnotifications_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_usersnotifications_aspnetusers_targetuserid FOREIGN KEY (target_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_roles (
  user_id text NOT NULL,
  role_id text NOT NULL,
  discriminator text NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_aspnetuserroles_aspnetroles_roleid FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT fk_aspnetuserroles_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT fk_aspnetuserroles_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_stripe_customer_mappings (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  customer_id text NOT NULL,
  card_detail_to_ke_n text,
  CONSTRAINT user_stripe_customer_mappings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_stripe_transaction_mappings (
  id uuid NOT NULL,
  user_id uuid,
  transaction_id text NOT NULL,
  status text NOT NULL,
  amount numeric NOT NULL,
  country text,
  zip_code text,
  requested_data text NOT NULL,
  response_data text NOT NULL,
  created_date timestamp with time zone,
  modified_date timestamp with time zone,
  webhook_execution_date timestamp with time zone,
  webhook_response_data text,
  webhook_status text,
  CONSTRAINT user_stripe_transaction_mappings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_tokens (
  user_id text NOT NULL,
  login_provider text NOT NULL,
  name text NOT NULL,
  value text,
  CONSTRAINT user_tokens_pkey PRIMARY KEY (user_id, login_provider, name),
  CONSTRAINT fk_aspnetusertokens_aspnetusers_userid FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id text NOT NULL,
  first_name text,
  last_name text,
  account_balance numeric,
  address text,
  is_approuve_required boolean,
  email_from_groups_on boolean,
  email_from_users_on boolean,
  is_active boolean,
  user_name text,
  normalized_user_name text,
  email text,
  normalized_email text,
  email_confirmed boolean,
  password_hash text,
  security_stamp text,
  concurrency_stamp text,
  phone_number text,
  phone_number_confirmed boolean,
  two_factor_enabled boolean,
  lockout_end timestamp with time zone,
  lockout_enabled boolean,
  access_failed_count integer NOT NULL,
  is_user_hidden boolean,
  date_created timestamp with time zone,
  picture_file_name text,
  opt_out_email_notifications boolean,
  is_free_user boolean,
  is_anonymous_investment boolean,
  consent_to_show_avatar boolean,
  is_exclude_user_balance boolean,
  alternate_email text,
  zip_code text,
  deleted_at timestamp with time zone,
  deleted_by text,
  is_deleted boolean,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_aspnetusers_aspnetusers_deletedby FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);