// <auto-generated />
using System;
using Invest.Repo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invest.Repo.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250930104914_AddedAssociatedFundIdAndIsPartOfFundColumnToCampaignTable")]
    partial class AddedAssociatedFundIdAndIsPartOfFundColumnToCampaignTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CampaignDtoGroup", b =>
                {
                    b.Property<int>("CampaignsId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.HasKey("CampaignsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("CampaignDtoGroup");
                });

            modelBuilder.Entity("Invest.Core.Models.AccountBalanceChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InvestmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NewValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PendingGrantsId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PendingGrantsId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountBalanceChangeLogs");
                });

            modelBuilder.Entity("Invest.Core.Models.ApprovedBy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApprovedBy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Impact Assets"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toniic Investors"
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.CampaignDto", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("AddedTotalAdminRaised")
                        .HasColumnType("int");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssociatedFundId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfoAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfoAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfoEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfoFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfoPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailSends")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ExpectedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FundraisingCloseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupForPrivateAccessId")
                        .HasColumnType("int");

                    b.Property<bool?>("HasExistingInvestors")
                        .HasColumnType("bit");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpactAssetsFundingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentInformationalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartOfFund")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWomenLed")
                        .HasColumnType("bit");

                    b.Property<string>("LogoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumInvestment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionAndVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NetworkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalPdfFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalizedThankYou")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredToCataCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDGs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Themes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TileImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupForPrivateAccessId");

                    b.HasIndex("UserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Invest.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mandatory = true,
                            Name = "Climate"
                        },
                        new
                        {
                            Id = 2,
                            Mandatory = true,
                            Name = "Gender"
                        },
                        new
                        {
                            Id = 3,
                            Mandatory = true,
                            Name = "Racial"
                        },
                        new
                        {
                            Id = 4,
                            Mandatory = true,
                            Name = "Poverty"
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.CompletedInvestmentsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfLastInvestment")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("Donors")
                        .HasColumnType("int");

                    b.Property<string>("InvestmentDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Themes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfInvestment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("CompletedInvestmentsDetails");
                });

            modelBuilder.Entity("Invest.Core.Models.DAFProviders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DAFProviders");
                });

            modelBuilder.Entity("Invest.Core.Models.FollowingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupToFollowId")
                        .HasColumnType("int");

                    b.Property<string>("RequestOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserToFollowId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupToFollowId");

                    b.HasIndex("RequestOwnerId");

                    b.HasIndex("UserToFollowId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Invest.Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApprouveRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorporateGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivateGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Invest.Core.Models.GroupAccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupAccountBalance");
                });

            modelBuilder.Entity("Invest.Core.Models.InvestmentFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalThemes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestedInvestmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RiskTolerance")
                        .HasColumnType("int");

                    b.Property<string>("Themes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("InvestmentFeedback");
                });

            modelBuilder.Entity("Invest.Core.Models.InvestmentNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("InvestmentNotes");
                });

            modelBuilder.Entity("Invest.Core.Models.InvestmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Venture Capital"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Private Equity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Private Debt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Small Business Lending"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Microfinance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Project Finance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cash Equivalents"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Emerging Markets"
                        },
                        new
                        {
                            Id = 9,
                            Name = "International Investing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Real Assets"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Real Estate"
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.LeaderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderGroup");
                });

            modelBuilder.Entity("Invest.Core.Models.PendingGrants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountAfterFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DAFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAFProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvestedSum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RejectionMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalInvestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("RejectedBy");

                    b.HasIndex("UserId");

                    b.ToTable("PendingGrants");
                });

            modelBuilder.Entity("Invest.Core.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PendingGrantsId")
                        .HasColumnType("int");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RejectionMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PendingGrantsId");

                    b.HasIndex("RejectedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("Invest.Core.Models.ReturnDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("InvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentageOfTotalInvestment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReturnAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReturnMasterId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnMasterId");

                    b.HasIndex("UserId");

                    b.ToTable("ReturnDetails");
                });

            modelBuilder.Entity("Invest.Core.Models.ReturnMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("MemoNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PrivateDebtEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PrivateDebtStartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ReturnAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalInvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalInvestors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ReturnMasters");
                });

            modelBuilder.Entity("Invest.Core.Models.ScheduledEmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingGrantId")
                        .HasColumnType("int");

                    b.Property<string>("ReminderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PendingGrantId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledEmailLogs");
                });

            modelBuilder.Entity("Invest.Core.Models.SchedulerLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Day3EmailCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Week2EmailCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchedulerLogs");
                });

            modelBuilder.Entity("Invest.Core.Models.Sdg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SDGs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "No poverty"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zero hunger"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Good health and well-being"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quality Education"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gender equality"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clean water and sanitation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Affordable and clean energy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Decent work and economic growth"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Industry, innovation and infrastructure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Reduced inequalities"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sustainable cities and economies"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Responsible consumption and production"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Climate action"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Life below water"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Life on land"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Peace, justice and strong institutions"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Partnership for the goals"
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.SystemValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DonationsIds",
                            Value = ""
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("AccountBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("EmailFromGroupsOn")
                        .HasColumnType("bit");

                    b.Property<bool?>("EmailFromUsersOn")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAnonymousInvestment")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApprouveRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFreeUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUserHidden")
                        .HasColumnType("bit");

                    b.Property<string>("KlaviyoProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("OptOutEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ccc24a6d-aa14-4f0e-ac7f-09740cb196f8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bde4dffa-8ac6-42c9-82e9-d2ea0c6d047a",
                            Email = "admin@aa.com",
                            EmailConfirmed = false,
                            EmailFromGroupsOn = false,
                            EmailFromUsersOn = false,
                            FirstName = "admin",
                            IsActive = false,
                            IsApprouveRequired = false,
                            IsFreeUser = false,
                            IsUserHidden = false,
                            LastName = "admin",
                            LockoutEnabled = true,
                            NormalizedUserName = "ADMIN1",
                            OptOutEmailNotifications = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKGOT9qPv6LK4JX2BuTAWMqWOyxMgY/5xa01QqSA8c0KfDDNRuqq9HLiwae1XKnnYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KLLPL3UL2TBHSLYEJS6ZRECUVFCVFFRZ",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("Invest.Core.Models.UserInvestments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LogTriggered")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInvestments");
                });

            modelBuilder.Entity("Invest.Core.Models.UsersNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlToRedirect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UsersNotifications");
                });

            modelBuilder.Entity("Invest.Core.Models.UserStripeCustomerMapping", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardDetailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserStripeCustomerMapping");
                });

            modelBuilder.Entity("Invest.Core.Models.UserStripeTransactionMapping", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("WebhookExecutionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WebhookResponseData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStripeTransactionMapping");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "460da70e-6557-4584-8fe2-03524ea7f5dc",
                            ConcurrencyStamp = "d06257e2-4ea8-4931-97f1-af0694b02c4d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Invest.Core.Models.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = "ccc24a6d-aa14-4f0e-ac7f-09740cb196f8",
                            RoleId = "460da70e-6557-4584-8fe2-03524ea7f5dc"
                        });
                });

            modelBuilder.Entity("CampaignDtoGroup", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", null)
                        .WithMany()
                        .HasForeignKey("CampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Invest.Core.Models.AccountBalanceChangeLog", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("Invest.Core.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Invest.Core.Models.PendingGrants", "PendingGrants")
                        .WithMany()
                        .HasForeignKey("PendingGrantsId");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Group");

                    b.Navigation("PendingGrants");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.CampaignDto", b =>
                {
                    b.HasOne("Invest.Core.Models.Group", "GroupForPrivateAccess")
                        .WithMany("PrivateCampaigns")
                        .HasForeignKey("GroupForPrivateAccessId");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("GroupForPrivateAccess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.CompletedInvestmentsDetails", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Invest.Core.Models.FollowingRequest", b =>
                {
                    b.HasOne("Invest.Core.Models.Group", "GroupToFollow")
                        .WithMany("Requests")
                        .HasForeignKey("GroupToFollowId");

                    b.HasOne("Invest.Core.Models.User", "RequestOwner")
                        .WithMany("Requests")
                        .HasForeignKey("RequestOwnerId");

                    b.HasOne("Invest.Core.Models.User", "UserToFollow")
                        .WithMany("RequestsToAccept")
                        .HasForeignKey("UserToFollowId");

                    b.Navigation("GroupToFollow");

                    b.Navigation("RequestOwner");

                    b.Navigation("UserToFollow");
                });

            modelBuilder.Entity("Invest.Core.Models.Group", b =>
                {
                    b.HasOne("Invest.Core.Models.User", "Owner")
                        .WithMany("Groups")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Invest.Core.Models.GroupAccountBalance", b =>
                {
                    b.HasOne("Invest.Core.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany("GroupBalances")
                        .HasForeignKey("UserId");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.InvestmentFeedback", b =>
                {
                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithOne("InvestmentFeedbacks")
                        .HasForeignKey("Invest.Core.Models.InvestmentFeedback", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.InvestmentNotes", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.LeaderGroup", b =>
                {
                    b.HasOne("Invest.Core.Models.Group", "Group")
                        .WithMany("LeadersGroup")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany("LeaderGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.PendingGrants", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("Invest.Core.Models.User", "RejectedByUser")
                        .WithMany()
                        .HasForeignKey("RejectedBy");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("RejectedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.Recommendation", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany("Recommendations")
                        .HasForeignKey("CampaignId");

                    b.HasOne("Invest.Core.Models.PendingGrants", "PendingGrants")
                        .WithMany()
                        .HasForeignKey("PendingGrantsId");

                    b.HasOne("Invest.Core.Models.User", "RejectedByUser")
                        .WithMany()
                        .HasForeignKey("RejectedBy");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Campaign");

                    b.Navigation("PendingGrants");

                    b.Navigation("RejectedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.ReturnDetails", b =>
                {
                    b.HasOne("Invest.Core.Models.ReturnMaster", "ReturnMaster")
                        .WithMany("ReturnDetails")
                        .HasForeignKey("ReturnMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReturnMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.ReturnMaster", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Invest.Core.Models.ScheduledEmailLog", b =>
                {
                    b.HasOne("Invest.Core.Models.PendingGrants", "PendingGrants")
                        .WithMany()
                        .HasForeignKey("PendingGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingGrants");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.UserInvestments", b =>
                {
                    b.HasOne("Invest.Core.Models.CampaignDto", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("Invest.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Invest.Core.Models.UsersNotification", b =>
                {
                    b.HasOne("Invest.Core.Models.User", "TargetUser")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Invest.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Invest.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invest.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Invest.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Invest.Core.Models.CampaignDto", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Invest.Core.Models.Group", b =>
                {
                    b.Navigation("LeadersGroup");

                    b.Navigation("PrivateCampaigns");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Invest.Core.Models.ReturnMaster", b =>
                {
                    b.Navigation("ReturnDetails");
                });

            modelBuilder.Entity("Invest.Core.Models.User", b =>
                {
                    b.Navigation("GroupBalances");

                    b.Navigation("Groups");

                    b.Navigation("InvestmentFeedbacks");

                    b.Navigation("LeaderGroups");

                    b.Navigation("Notifications");

                    b.Navigation("Requests");

                    b.Navigation("RequestsToAccept");
                });
#pragma warning restore 612, 618
        }
    }
}
